name: workflows
on:
  push:
    branches:
      - feat-laboratorio

jobs:
  Build:
    runs-on: ubuntu-lastest
    steps:

    - name: Prueba 1 compilacion
      run: |
      echo "Prueba de compilacion de laboratorio final"