name: workflows
on:
  push:
    branches:
      - feat-laboratorio

jobs:        
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build


   
