name: workflows
on:
  push:
    branches:
      - feat-laboratorio

jobs:        
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
        uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
          
    - name: Install
        run: npm ci